name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter_local_notifications: ^17.2.2
  rxdart: ^0.28.0
  flutter_timezone: ^3.0.0
  flutter_styled_toast: ^2.2.1
  floor: ^1.5.0
  sqflite: ^2.3.3+1
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.6
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
